name: Platformer
description: >
  Platformer Game
version: 1.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: any
  logger: any
  flame: ^1.1.1
  flame_audio: ^1.0.2
  forge2d: ^0.11.0
  wakelock: any
  provider: any
  google_fonts: any
  get_storage: any
  font_awesome_flutter: any
  vibration: ^1.7.4-nullsafety.0



  flutter:
    sdk: flutter
  cupertino_icons: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/audio/sfx/
